source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-browserid', :git => 'https://github.com/onli/sinatra-browserid'
gem 'sqlite3'
gem 'puma'
gem 'rack-superfeedr'
gem 'nokogiri'
gem 'sinatra-hijacker'
