source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-browserid', :git => 'https://github.com/sch1zo/sinatra-browserid'
gem 'sqlite3'
gem 'puma'
gem 'rack-superfeedr'
gem 'emk-sinatra-url-for'
gem 'nokogiri'
